/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HipaaRouteImport } from './routes/hipaa'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaRoute = HipaaRouteImport.update({
  id: '/hipaa',
  path: '/hipaa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/hipaa': typeof HipaaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/hipaa': typeof HipaaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/hipaa': typeof HipaaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/client-portal'
    | '/contact'
    | '/hipaa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/industries/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/client-portal'
    | '/contact'
    | '/hipaa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog'
    | '/industries'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/client-portal'
    | '/contact'
    | '/hipaa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/industries/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ClientPortalRoute: typeof ClientPortalRoute
  ContactRoute: typeof ContactRoute
  HipaaRoute: typeof HipaaRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa': {
      id: '/hipaa'
      path: '/hipaa'
      fullPath: '/hipaa'
      preLoaderRoute: typeof HipaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ClientPortalRoute: ClientPortalRoute,
  ContactRoute: ContactRoute,
  HipaaRoute: HipaaRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
